# Available placeholders: {UUID},{UUID-},{USERNAME}
# {UUID-}: UUID of the player without "-"
url: "https://minotar.net/skin/{UUID}"









# ==============================================
#        THIS IS UNLIKELY TO BE NECESARRY
#    SO YOU PROBABLY DON'T NEED TO TOUCH THIS
# ==============================================
#  It could be necessary, however, if you, for example, have a very old world, and are using BlueMap Offline Player Markers.

# If we don't know the Username of the player with this UUID, we will use this URL to get the Username from the UUID
# Leave empty to just use the UUID (as the Username) after all
# Available placeholders: {UUID},{UUID-}
# {UUID-}: UUID of the player without "-"
username-url: "https://sessionserver.mojang.com/session/minecraft/profile/{UUID}"
# The JSON Path to the Username in the response of the username-url
# Format explained here: https://github.com/json-path/JsonPath
json-path: "$.name"

#username-url: "https://playerdb.co/api/player/minecraft/{UUID}"
#json-path: "$.data.player.username"

#username-url: "https://api.minetools.eu/uuid/{UUID}"
#json-path: "$.name"

#username-url: ""
#json-path: ""
